#!/usr/bin/env python3
"""
TCD/TC Generator — fills template and appends source attribution.
================================================================

Generates local TCD/TC files by applying a template and appending
source attribution. Domain-agnostic — works for ISH, LPSS, THC, etc.

Usage:
  # Generate a new TCD from CLI args
  python tcd_generator.py --template templates/tcd_template.md \
    --output ./tcd_output/TCD_heci_connect_basic_20260403.md \
    --field TC_TITLE="HECI Connection Establishment" \
    --field TEST_CATEGORY="HECI Transport" \
    --source "ISH IP HAS|Chapter 5.2|https://chat.co-design.intel.com/chat|2026-04-03" \
    --source "HSDES #12345678|Full article|https://hsdes.intel.com/appstore/article/#/12345678|2026-04-03"

  # Generate from a JSON spec (bulk mode)
  python tcd_generator.py --template templates/tcd_template.md \
    --json batch_spec.json \
    --output-dir ./tcd_output/batch_heci_20260403/

  # Amend mode (requires explicit confirmation flag)
  python tcd_generator.py --template templates/tcd_template.md \
    --existing existing_tcd.md \
    --output ./tcd_output/TCD_12345678_amended_20260403.md \
    --mode amend --user-confirmed

Output: Local markdown files only
"""

import os
import sys
import json
import argparse
from datetime import datetime


def load_template(template_path):
    """Load the TCD/TC template file."""
    if not os.path.exists(template_path):
        print(json.dumps({
            "status": "error",
            "error": f"Template file not found: {template_path}"
        }))
        sys.exit(1)

    with open(template_path, 'r', encoding='utf-8') as f:
        return f.read()


def fill_template(template_content, field_values):
    """
    Replace {{FIELD_NAME}} placeholders in the template with provided values.
    Leaves unfilled placeholders as [TODO: FIELD_NAME] markers.
    """
    filled = template_content
    filled_count = 0
    todo_count = 0

    # Find all placeholders
    import re
    placeholders = set(re.findall(r'\{\{(\w+)\}\}', template_content))

    for placeholder in placeholders:
        token = '{{' + placeholder + '}}'
        if placeholder in field_values and field_values[placeholder]:
            filled = filled.replace(token, str(field_values[placeholder]))
            filled_count += 1
        else:
            filled = filled.replace(token, f'[TODO: {placeholder}]')
            todo_count += 1

    return filled, filled_count, todo_count


def build_source_attribution(sources, skill_version="1.0"):
    """
    Build the mandatory Sources & References section.

    Args:
        sources: List of dicts with keys: name, section, link, date
                 OR list of pipe-delimited strings: "name|section|link|date"
    """
    today = datetime.now().strftime("%Y-%m-%d")

    lines = [
        "",
        "---",
        "",
        "## Sources & References",
        "",
        "| # | Source Document | Section/Page | Link | Date Accessed |",
        "|---|----------------|-------------|------|---------------|"
    ]

    for i, src in enumerate(sources, 1):
        if isinstance(src, dict):
            name = src.get("name", "[Unknown]")
            section = src.get("section", "-")
            link = src.get("link", "-")
            date = src.get("date", today)
        elif isinstance(src, str) and "|" in src:
            parts = src.split("|")
            name = parts[0] if len(parts) > 0 else "[Unknown]"
            section = parts[1] if len(parts) > 1 else "-"
            link = parts[2] if len(parts) > 2 else "-"
            date = parts[3] if len(parts) > 3 else today
        else:
            name = str(src)
            section = "-"
            link = "-"
            date = today

        lines.append(f"| {i} | {name} | {section} | {link} | {date} |")

    lines.extend([
        "",
        "### Source Notes",
        f"- **Generated by**: TCD Skill v{skill_version} on {today}",
        ""
    ])

    return "\n".join(lines)


def generate_tcd(template_path, output_path, field_values, sources,
                 mode="new", existing_content=None, user_confirmed=False):
    """
    Generate a TCD/TC file.

    Args:
        template_path: Path to the template file
        output_path: Path for the output file
        field_values: Dict of field_name → value
        sources: List of source entries for attribution
        mode: 'new' or 'amend'
        existing_content: Original TCD content (required for amend mode)
        user_confirmed: Must be True for amend mode
    """
    # Amend safety check
    if mode == "amend" and not user_confirmed:
        print(json.dumps({
            "status": "blocked",
            "mode": "amend",
            "message": "Amend mode requires explicit user confirmation. "
                       "Pass --user-confirmed flag after user reviews the diff."
        }))
        sys.exit(1)

    # Load and fill template
    template = load_template(template_path)
    filled, filled_count, todo_count = fill_template(template, field_values)

    # Add source attribution
    source_section = build_source_attribution(sources)
    final_content = filled + source_section

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)

    # Write output
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(final_content)

    result = {
        "status": "ok",
        "mode": mode,
        "output_file": output_path,
        "fields_filled": filled_count,
        "todos_remaining": todo_count,
        "sources_attributed": len(sources),
        "message": f"TCD generated: {output_path} ({filled_count} fields filled, {todo_count} TODOs remaining)"
    }
    print(json.dumps(result, indent=2))


def generate_batch(template_path, output_dir, json_spec_path):
    """
    Generate multiple TCDs from a JSON specification file.

    JSON spec format:
    {
      "batch_name": "ISH HECI Tests",
      "tcds": [
        {
          "filename": "TCD_heci_connect_basic.md",
          "fields": { "TC_TITLE": "...", ... },
          "sources": [ {"name": "...", "section": "...", "link": "...", "date": "..."} ]
        },
        ...
      ]
    }
    """
    with open(json_spec_path, 'r', encoding='utf-8') as f:
        spec = json.load(f)

    os.makedirs(output_dir, exist_ok=True)

    results = []
    for tcd_spec in spec.get("tcds", []):
        filename = tcd_spec.get("filename", f"TCD_unnamed_{len(results)+1}.md")
        output_path = os.path.join(output_dir, filename)
        fields = tcd_spec.get("fields", {})
        sources = tcd_spec.get("sources", [])

        template = load_template(template_path)
        filled, filled_count, todo_count = fill_template(template, fields)
        source_section = build_source_attribution(sources)
        final_content = filled + source_section

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(final_content)

        results.append({
            "filename": filename,
            "fields_filled": filled_count,
            "todos_remaining": todo_count,
            "sources": len(sources)
        })

    # Create batch index
    index_path = os.path.join(output_dir, f"batch_index_{datetime.now().strftime('%Y%m%d')}.md")
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write(f"# TCD Batch Index — {spec.get('batch_name', 'Unnamed Batch')}\n\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
        f.write("| # | File | Fields Filled | TODOs | Sources |\n")
        f.write("|---|------|--------------|-------|--------|\n")
        for i, r in enumerate(results, 1):
            f.write(f"| {i} | [{r['filename']}]({r['filename']}) | {r['fields_filled']} | {r['todos_remaining']} | {r['sources']} |\n")

    print(json.dumps({
        "status": "ok",
        "mode": "batch",
        "output_dir": output_dir,
        "tcds_generated": len(results),
        "index_file": index_path,
        "details": results
    }, indent=2))


def main():
    parser = argparse.ArgumentParser(
        description="TCD/TC Generator — fill template and append source attribution",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument("--template", required=True,
                        help="Path to the TCD/TC template file")
    parser.add_argument("--output", type=str, default=None,
                        help="Output file path (single TCD mode)")
    parser.add_argument("--output-dir", type=str, default=None,
                        help="Output directory (batch mode)")
    parser.add_argument("--mode", choices=["new", "amend"], default="new",
                        help="Generation mode: 'new' or 'amend'")
    parser.add_argument("--existing", type=str, default=None,
                        help="Path to existing TCD file (amend mode)")
    parser.add_argument("--user-confirmed", action="store_true",
                        help="Explicit flag confirming user has reviewed amend diff")
    parser.add_argument("--field", action="append", default=[],
                        help="Field value in KEY=VALUE format (repeatable)")
    parser.add_argument("--source", action="append", default=[],
                        help="Source in 'name|section|link|date' format (repeatable)")
    parser.add_argument("--json", type=str, default=None,
                        help="JSON spec file for batch generation")

    args = parser.parse_args()

    # Parse field key=value pairs
    field_values = {}
    for fv in args.field:
        if "=" in fv:
            key, val = fv.split("=", 1)
            field_values[key.strip()] = val.strip()

    # Batch mode
    if args.json:
        if not args.output_dir:
            args.output_dir = f"./tcd_output/batch_{datetime.now().strftime('%Y%m%d')}"
        generate_batch(args.template, args.output_dir, args.json)
        return

    # Single TCD mode
    if not args.output:
        args.output = f"./tcd_output/TCD_generated_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"

    existing = None
    if args.mode == "amend" and args.existing:
        with open(args.existing, 'r', encoding='utf-8') as f:
            existing = f.read()

    generate_tcd(
        template_path=args.template,
        output_path=args.output,
        field_values=field_values,
        sources=args.source,
        mode=args.mode,
        existing_content=existing,
        user_confirmed=args.user_confirmed
    )


if __name__ == "__main__":
    main()
